"""
core/scoring — Response controller.

Applies adaptive response policies based on hallucination risk:

  LOW      → pass through unchanged
  MEDIUM   → add a disclaimer footer
  HIGH     → rewrite with hedged language + cite sources
  CRITICAL → refuse and explain why
"""

from __future__ import annotations

import httpx

from core.config import get_settings
from core.logging import get_logger
from core.models import (
    ControllerAction,
    Document,
    HallucinationReport,
    RiskLevel,
)

logger = get_logger(__name__)
_settings = get_settings()

_REWRITE_PROMPT = """\
The following AI-generated answer may contain inaccurate claims. \
Rewrite it to be more cautious and accurate based on the provided sources. \
Add inline citations like (Source: X) where relevant. \
Do not add medical disclaimers — those are handled separately.

Original answer:
{answer}

Verified sources:
{sources}

Rewrite the answer now:
"""

_DISCLAIMER = (
    "\n\n---\n"
    "⚠️  This response was generated by an AI and may contain inaccuracies. "
    "Always verify critical information with authoritative sources."
)


class ResponseController:
    """
    Applies an adaptive policy to a raw LLM answer given its HallucinationReport.
    """

    def __init__(self, ollama_url: str | None = None, model: str | None = None):
        self._url = (ollama_url or _settings.ollama_base_url) + "/api/generate"
        self._model = model or _settings.ollama_model

    async def control(
        self,
        raw_answer: str,
        report: HallucinationReport,
        extra_disclaimer: str = "",
    ) -> tuple[str, ControllerAction]:
        """
        Returns (safe_answer, action_taken).
        """
        risk = report.overall_risk

        if risk == RiskLevel.LOW:
            answer = raw_answer + (extra_disclaimer or "")
            action = ControllerAction.PASS_THROUGH

        elif risk == RiskLevel.MEDIUM:
            answer = raw_answer + _DISCLAIMER + (extra_disclaimer or "")
            action = ControllerAction.ADD_DISCLAIMER

        elif risk == RiskLevel.HIGH:
            rewritten = await self._rewrite(raw_answer, report.retrieved_documents)
            answer = rewritten + _DISCLAIMER + (extra_disclaimer or "")
            action = ControllerAction.REWRITE

        else:  # CRITICAL
            answer = self._refusal(report) + (extra_disclaimer or "")
            action = ControllerAction.REFUSE

        logger.info(
            "controller.action",
            risk=risk,
            action=action,
            score=report.risk_score,
        )
        return answer, action

    async def _rewrite(self, answer: str, docs: list[Document]) -> str:
        sources = "\n".join(
            f"- {d.source} (relevance {d.score:.2f}): {d.content[:300]}" for d in docs[:5]
        )
        prompt = _REWRITE_PROMPT.format(answer=answer, sources=sources)
        try:
            async with httpx.AsyncClient(timeout=60) as client:
                resp = await client.post(
                    self._url,
                    json={"model": self._model, "prompt": prompt, "stream": False},
                )
                resp.raise_for_status()
            return resp.json().get("response", answer).strip()
        except Exception as exc:
            logger.warning("controller.rewrite_failed", error=str(exc))
            return answer

    @staticmethod
    def _refusal(report: HallucinationReport) -> str:
        unsupported = [
            v.claim.text
            for v in report.claim_verdicts
            if not v.supported
        ]
        lines = [
            "❌ This response has been blocked due to a high hallucination risk score "
            f"({report.risk_score:.2f}/1.0).",
            "",
            "The following claims could not be verified against any retrieved source:",
        ]
        for claim in unsupported[:5]:
            lines.append(f"  • {claim}")
        lines += [
            "",
            "Please rephrase your query or consult a domain expert.",
        ]
        return "\n".join(lines)
